### ISSUE TITLE
Need to automate restarts stateful/stateless

### ISSUE THREAD

**Issue by ibaldin** [fabric-testbed/ControlFramework#144]
Since sometimes we need to start/restart mutliple AMs/actors at once we should automate this process so only a minimal input is required.

**Comment by mcevik0** [comment]
As one part essentially clean-restart can be performed with the steps in [Install Control Framework]( https://fabric-testbed.atlassian.net/wiki/spaces/FP/pages/109641729/Hank+Installation+Configuration+and+Testing#4.11-Install-Control-Framework) section. 

```
SITE="<SITE_NAME>"
INVENTORY="fabric-hosts"
PLAYBOOK="site.yml"
LIMIT="${SITE}_head"

# Stop and clean

ansible-playbook -i ${INVENTORY} ${PLAYBOOK} --limit ${LIMIT} --tags "software-cf-authority-teardown"

# Updates (eg. aggregate-ads are copied) should be done and 
# variables should be adjusted (eg. software versions) as described 
# in the referenced doc above


# Deploy and start 

ansible-playbook -i ${INVENTORY} ${PLAYBOOK} --limit ${LIMIT} --tags "software-cf-cert"
ansible-playbook -i ${INVENTORY} ${PLAYBOOK} --limit ${LIMIT} --tags "software-cf-aggregate-ads"
ansible-playbook -i ${INVENTORY} ${PLAYBOOK} --limit ${LIMIT} --tags "software-cf-directory"
ansible-playbook -i ${INVENTORY} ${PLAYBOOK} --limit ${LIMIT} --tags "software-cf-checkout"
ansible-playbook -i ${INVENTORY} ${PLAYBOOK} --limit ${LIMIT} --tags "software-cf-inventory"
ansible-playbook -i ${INVENTORY} ${PLAYBOOK} --limit ${LIMIT} --tags "software-cf-authority-setup"
ansible-playbook -i ${INVENTORY} ${PLAYBOOK} --limit ${LIMIT} --tags "software-cf-authority-setup-docker"
ansible-playbook -i ${INVENTORY} ${PLAYBOOK} --limit ${LIMIT} --tags "software-cf-authority-setup-kafka"
ansible-playbook -i ${INVENTORY} ${PLAYBOOK} --limit ${LIMIT} --tags "software-cf-authority-run-docker"
```

**Comment by mcevik0** [comment]
```
#
# Stop containers 
#
INVENTORY="fabric-hosts"
PLAYBOOK="site.yml"
LIMIT="salt-hn"
TAGS="software-cf-authority-stop-containers"
ansible-playbook -i ${INVENTORY} ${PLAYBOOK} --limit ${LIMIT} --tags ${TAGS}

#
# Stop and remove containers (removal of volumes and/or images can be added)
#
INVENTORY="fabric-hosts"
PLAYBOOK="site.yml"
LIMIT="salt-hn"
TAGS="software-cf-authority-stop-remove-containers"
ansible-playbook -i ${INVENTORY} ${PLAYBOOK} --limit ${LIMIT} --tags ${TAGS}

#
# Start containers
#
INVENTORY="fabric-hosts"
PLAYBOOK="site.yml"
LIMIT="salt-hn"
TAGS="software-cf-authority-start-containers"
ansible-playbook -i ${INVENTORY} ${PLAYBOOK} --limit ${LIMIT} --tags ${TAGS}

#
# Redeploy ads
#
INVENTORY="fabric-hosts"
PLAYBOOK="site.yml"
LIMIT="salt-hn"
TAGS="software-cf-aggregate-ads-redeploy"
ansible-playbook -i ${INVENTORY} ${PLAYBOOK} --limit ${LIMIT} --tags ${TAGS}
```

**Comment by ibaldin** [comment]
There are two things I want to incorporate. Basically there should be a restart clean/stateful and with and without model update and I believe these can be independent. I.e. you can have a stateful restart with model update. The other dimension is automatically cleaning up any stale slivers if it is a clean restart - this seems like a must - CF should call a 'close' on all slivers touching on the AM /actor being restarted. We need to discuss some more but if we implement these two things, restarts will become a lot less painful, esp. if model updates can be done statefully. 

My sense is stateful model update is actually OK. Yes - something has changed in the model, we can undelegate, redelegate (all this means is unmerging/merging AM ADM graph from broker without touching existing reservations). We already have all the info we need to close reservations stored in Postgres, so model update doesn't affect it. I expect the vast majoriy of reasons why we restart AMs will be minor model updates and as such we can make them painless to the users.

**Comment by kthare10** [comment]
Steps to follow for stateful restart with model updates for an AM:
- Un-delegate resources for the AM from the Broker
- Create a file inside the AM container at the location: `/usr/src/app/reload.model`
- Stop the AM container 
- Copy the new ARM
- Start the AM container
- After recovery, the temporary file would be deleted by CF
- Re-delegate resources from the AM to the Broker
