### ISSUE TITLE
Logging question

### ISSUE THREAD

**Issue by ibaldin** [fabric-testbed/ControlFramework#149]
Log messages seen in actor.log vs via `docker container logs` are different - which ones are being logged to ELK?

**Comment by kthare10** [comment]
logs from actor.log are being sent to ELK. `docker logs <container>` only show rdkafka logs. I'll explore more to see if there is a way to also redirect them to actor.log

**Comment by ibaldin** [comment]
We should close this now that we have a better approach to logging.
