### ISSUE TITLE
Orchestrator API Update Request

### ISSUE THREAD

**Issue by yaxue1123** [fabric-testbed/ControlFramework#155]
**GET /slices**

- [ ] If the user has no slices, the GET /slices request will return a 404 error with a message "User# has no slice". Could it be updated to return 200 success with response body with empty "slices" field?
- [ ] Besides the "lease_end" field, could the response also include "creation_time" for each slice? So that portal could sort the results by most recent created slices, and users can manage their slices more easily if they have many of them.

**GET /slices/{sliceID}**

- [ ] The current response body only include "message", "slice_model" and "status". Could it be updated to include all slice information such as "slice_name", "slice_id", "graph_id" and "lease_end"?  In this way the portal slice viewer page could use these information directly without additional API call to GET /slices again and filter the particular slice information. 

**Directed or Undirected Graph**

Should the links with class "has" be directed that source has target? This is the most common situation but with some exceptions.  The normal relationship (source -> target) is VM has SmartNIC, and SmartNIC has OVS. But sometimes they are the opposite.

Ideal "has" relationship chain: Site -> NetworkNode (VM) -> Component (NIC) -> NetworkService -> (OVS) -> ConnectionPoint. Otherwise the frontend slice parser needs to deal with double amounts of situation and there will be a lot of redundant if/ else statements.

**Comment by ibaldin** [comment]
@yaxue1123 is the issue about directed vs undirected graphs still relevant? I remember we had a discussion about it earlier.

**Comment by yaxue1123** [comment]
> @yaxue1123 is the issue about directed vs undirected graphs still relevant? I remember we had a discussion about it earlier.

@ibaldin Yes currently portal adds a lot of if else statements to figure out parent-child relationship of the "has" links. If the relationship could always be parent "has" child, it will be much easier and saving a lot of code for the slice parser.
